#!/usr/bin/env python3
"""Package the repo as importable `.skill` bundles.

A `.skill` file is a zip archive with a `SKILL.md` at its root — the format
Claude accepts for an uploaded skill. Two shapes are produced:

  dist/yazhi-skills.skill        one bundle, all 51 skills. Its root SKILL.md is
                                 a generated router: it lists every skill with
                                 its trigger and the bundled path to read.
  dist/skills/<name>.skill       one bundle per skill, that skill's SKILL.md at
                                 the archive root. Built with --per-skill.

A bundle must contain exactly one SKILL.md — the one at its root that defines
the skill. So in the collection bundle the 51 skill bodies ship as reference
files under references/<category>/<name>.md, not under their repo paths, which
would put 51 further SKILL.md files in the archive and make it invalid.

Archives are byte-for-byte reproducible (fixed timestamps, sorted entries) so
`--check` can tell a stale bundle from an unchanged one.

Usage:
    python3 scripts/build_skill_bundle.py [--per-skill] [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lib_skills import (  # noqa: E402
    REPO_ROOT,
    Skill,
    categories,
    discover,
    title_for,
)

DIST = REPO_ROOT / "dist"
BUNDLE = DIST / "yazhi-skills.skill"
PER_SKILL_DIR = DIST / "skills"

# Fixed epoch for every archive member: zip's own 1980-01-01 floor.
FIXED_DATE = (1980, 1, 1, 0, 0, 0)

def bundled_path(skill: Skill) -> str:
    """Where a skill's body lives inside the collection bundle.

    Deliberately not the repo path: the file is renamed away from SKILL.md so
    the archive holds exactly one, the router at the root.
    """
    return f"references/{skill.category}/{skill.name}.md"


ROUTER_NAME = "yazhi-skills"
ROUTER_DESCRIPTION = (
    "Use when a task touches any area this collection covers — forward-deployed "
    "engineering, AI/ML systems, sovereign or air-gapped AI, security review, "
    "Tamil language and script, computer-use agents, developer tooling, or "
    "helping a ~12-year-old learn, decide, and stay safe. Points you at the one "
    "detailed skill file for the task so you follow its checklist instead of "
    "improvising."
)


def readme_summaries() -> dict[str, str]:
    """Map skill name -> the hand-written 'Covers' cell from the README catalog.

    The README is the only place those one-line summaries exist; the frontmatter
    description is a full trigger sentence and too long for a router table.
    """
    readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    pattern = re.compile(r"^\| \[`([a-z0-9-]+)`\]\([^)]+\) \| (.+?) \|$", re.M)
    return {m.group(1): m.group(2).strip() for m in pattern.finditer(readme)}


def render_router(skills: list[Skill]) -> str:
    summaries = readme_summaries()
    cats = categories(skills)

    lines = [
        "---",
        f"name: {ROUTER_NAME}",
        f"description: {ROUTER_DESCRIPTION}",
        "---",
        "",
        f"This bundle carries {len(skills)} self-contained skills across "
        f"{len(cats)} areas, one file each under `references/`. Every skill is "
        "a procedural checklist with concrete defaults and a named set of "
        "failure modes — the detail that makes them worth following lives in "
        "those files, not in this index.",
        "",
        "## How to use this bundle",
        "",
        "1. Find the row below whose trigger matches the task in front of you.",
        "2. Read that file from this bundle before acting — the summaries here "
        "are only enough to choose, never enough to execute.",
        "3. Follow its workflow section in order, and check the anti-patterns "
        "section before you finish.",
        "4. Skills cross-reference each other by name in backticks. When one "
        "points at another, find that name in the tables below and read its "
        "file too rather than guessing at what it says.",
        "",
        "If nothing matches, this bundle does not cover the task — say so and "
        "work without it rather than stretching an unrelated skill to fit.",
        "",
    ]

    for cat in cats:
        in_cat = [s for s in skills if s.category == cat]
        lines.append(f"## {title_for(cat)} ({len(in_cat)})")
        lines.append("")
        lines.append("| Skill | Use it when | File |")
        lines.append("|---|---|---|")
        for skill in sorted(in_cat, key=lambda s: s.name):
            summary = summaries.get(skill.name, skill.description[:120])
            lines.append(f"| `{skill.name}` | {summary} | `{bundled_path(skill)}` |")
        lines.append("")

    lines.append(
        "Generated by scripts/build_skill_bundle.py from the yazhi-skills "
        "repository — https://github.com/yazhi-lem/yazhi-skills"
    )
    return "\n".join(lines) + "\n"


def write_zip(path: Path, members: list[tuple[str, str]]) -> bytes:
    """Write a deterministic zip and return its bytes."""
    import io

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in sorted(members):
            info = zipfile.ZipInfo(name, date_time=FIXED_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, content)
    return buffer.getvalue()


def collection_members(skills: list[Skill]) -> list[tuple[str, str]]:
    members = [("SKILL.md", render_router(skills))]
    for skill in skills:
        members.append((bundled_path(skill), skill.path.read_text(encoding="utf-8")))
    members.append(("LICENSE", (REPO_ROOT / "LICENSE").read_text(encoding="utf-8")))

    skill_mds = [name for name, _ in members if Path(name).name == "SKILL.md"]
    if skill_mds != ["SKILL.md"]:
        raise AssertionError(f"bundle must hold exactly one SKILL.md, got {skill_mds}")
    return members


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--per-skill",
        action="store_true",
        help="also write dist/skills/<name>.skill, one per skill",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if a committed bundle is out of date",
    )
    args = parser.parse_args()

    skills = discover()
    targets: list[tuple[Path, bytes]] = [
        (BUNDLE, write_zip(BUNDLE, collection_members(skills)))
    ]

    if args.per_skill:
        for skill in skills:
            targets.append(
                (
                    PER_SKILL_DIR / f"{skill.name}.skill",
                    write_zip(
                        PER_SKILL_DIR / f"{skill.name}.skill",
                        [("SKILL.md", skill.path.read_text(encoding="utf-8"))],
                    ),
                )
            )

    if args.check:
        stale = [
            p.relative_to(REPO_ROOT).as_posix()
            for p, data in targets
            if not p.exists() or p.read_bytes() != data
        ]
        if stale:
            print(
                "out of date: " + ", ".join(stale) + "\n"
                "run: python3 scripts/build_skill_bundle.py",
                file=sys.stderr,
            )
            return 1
        print(f"{len(targets)} bundle(s) up to date")
        return 0

    for path, data in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    rel = BUNDLE.relative_to(REPO_ROOT).as_posix()
    print(f"wrote {rel} ({len(targets[0][1]):,} bytes, {len(skills)} skills)")
    if args.per_skill:
        print(f"wrote {len(targets) - 1} per-skill bundles in dist/skills/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
